version: '2.1'

services:
  nginx:
      image: nginx:1.13.7
      container_name: nginx
      depends_on:
          - file_manager
      volumes:
          - ./ngnix/nginx.conf:/etc/nginx/conf.d/default.conf
      networks:
          - my-network
      ports:
          - 80:80
  file_manager:
    image: file_manager
    build: .
    depends_on:
     - pureftpd
    volumes:
      - ../:/app
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./main.py
    command: flask run --host=0.0.0.0
    networks:
      my-network:
        aliases:
        - flask-app
  pureftpd:
    build: pureftpd
    container_name: pureftpd
    ports:
      - "21:21"
    volumes:
      - ./data/ftpuser:/home/ftpuser
      - ./data/pure-ftpd:/etc/pure-ftpd
    privileged: true
    restart: always
networks:
    my-network: